# auto-generated by some random Python script
require [ "fileinto" ];

if allof (
    address :is :domain "to" "example.org",
    not address :is :localpart "to" [
        "foobar2000"
    ]
) {
    fileinto "Junk";
    stop;
}
